// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCToXZpPmeEy2SDbMY4ye4GgqzBGMAR2iE',
    appId: '1:184402284558:web:1c810d408d34a13cecac5f',
    messagingSenderId: '184402284558',
    projectId: 'wathiq-qa',
    authDomain: 'wathiq-qa.firebaseapp.com',
    storageBucket: 'wathiq-qa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBkv76hvh6q1WFoFq_BB50CACVbBBRXpg',
    appId: '1:184402284558:android:66fd82be15dd6c16ecac5f',
    messagingSenderId: '184402284558',
    projectId: 'wathiq-qa',
    storageBucket: 'wathiq-qa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdV3qU9QFW7V3YX5qkGUEhnXRAGAM5hF8',
    appId: '1:184402284558:ios:699fe273478b04ececac5f',
    messagingSenderId: '184402284558',
    projectId: 'wathiq-qa',
    storageBucket: 'wathiq-qa.firebasestorage.app',
    iosBundleId: 'com.wathiq.app.wathiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdV3qU9QFW7V3YX5qkGUEhnXRAGAM5hF8',
    appId: '1:184402284558:ios:699fe273478b04ececac5f',
    messagingSenderId: '184402284558',
    projectId: 'wathiq-qa',
    storageBucket: 'wathiq-qa.firebasestorage.app',
    iosBundleId: 'com.wathiq.app.wathiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCToXZpPmeEy2SDbMY4ye4GgqzBGMAR2iE',
    appId: '1:184402284558:web:d056826ac82e06b5ecac5f',
    messagingSenderId: '184402284558',
    projectId: 'wathiq-qa',
    authDomain: 'wathiq-qa.firebaseapp.com',
    storageBucket: 'wathiq-qa.firebasestorage.app',
  );
}
